### ISSUE TITLE
пример миграции

### ISSUE THREAD

**Issue by AlimovRoostam** [paulzi/yii2-auto-tree#1]
Покажите пример миграции пожалуйста

**Comment by paulzi** [comment]
Пример миграции можете найти в behaviors, которые будете подключать для
хранения. Например, paulzi/yii2-adjacency-list. Autotree нужен для
совмещения нескольких структур хранения. Например итоговой миграции Al+MP:

``` php
$this->createTable('{{%tree}}', [
            'id'    => Schema::TYPE_PK,
            'parent_id' => Schema::TYPE_INTEGER . ' NULL',
            'path'  => Schema::TYPE_STRING . ' NULL',
            'depth' => Schema::TYPE_INTEGER . ' NOT NULL',
            'sort'  => Schema::TYPE_INTEGER . ' NOT NULL',
            'name'  => Schema::TYPE_STRING . ' NOT NULL', // example field
        ], $tableOptions);
        $this->createIndex('path', '{{%tree}}', ['path']);
        $this->createIndex('parent_sort', '{{%tree}}', ['parent_id',
'sort']);
```

2 Июл 2016 г. 18:35 пользователь "Roostam" notifications@github.com
написал:

**Comment by AlimovRoostam** [comment]
Спасибо, есть ли возможность использовать все виды бехейвиров? Чтобы в будущем можно было переключаться с одного на другой? И как тогда будет выглядеть миграция. Заранее спасибо за ваш ответ.

На данный момент храню в Nested Sets

**Comment by paulzi** [comment]
Подключить то можно, но это будет замедлять операции. Поменять структуру хранения и подключить нужные поведения можно в любое время, нужно будет добавить нужные колонки в базу, и единожны просчитать их значения. В коде придется поменять лишь behavior типа хранения дерева.
Но вообще я рекомендую связку Al+MP или AL+NS, вместо чистого nested sets это быстрее работает.

**Comment by AlimovRoostam** [comment]
Спасибо Вам большое за совет. Буду пробывать

**Comment by AlimovRoostam** [comment]
Подскажите связка AL+NS правильна ли

`$this->createTable('{{%pages}}', [
            'id'    => $this->primaryKey(),
            'tree'  => $this->integer(),
            'lft'   => $this->integer()->notNull(),
            'rgt'   => $this->integer()->notNull(),
            'depth' => $this->integer()->notNull(),
            'parent_id' => $this->integer(),
            'sort' => $this->integer(),

```
    ], $tableOptions);
    $this->createIndex('lft', '{{%pages}}', ['tree', 'lft', 'rgt']);
    $this->createIndex('rgt', '{{%pages}}', ['tree', 'rgt']);
    $this->createIndex('parent_sort', '{{%pages}}', ['parent_id', 'sort']);`
```

**Comment by paulzi** [comment]
Всё верно, единственное примечание - поле sort тут не обязательно. Если поле sort будет - то можно в любой момент можно отключить NS поведение, и всё будет работать без дополнительных телодвижений, с сохранением порядка узлов. Если поле sort не будет (и в настройках AL указать sortable => false), то если отключить NS - порядок не сохранится, но зато этот вариант производительней.
На мой взгляд оптимальнее не добавлять поле sort, если вы всё-таки в будущем решите отказаться от NS поле sort легко добавить и автоматически заполнить на основе lft.

**Comment by AlimovRoostam** [comment]
Если я все таки решу оставить поле sort. В модели поведения такие

`
 use AutoTreeTrait;
`

`['class' => AdjacencyListBehavior::className()],`
`
[
                'class' => NestedSetsBehavior::className(),
                'treeAttribute' => 'tree',
            ],
`

При сохранении кажный корень дерева +100 дочерние элементы имеют sort 0 так и должно быть?

**Comment by paulzi** [comment]
Да, для новых дочерних узлов выставляется sort = 0. Для корневых узлов поле sort в принципе не имеет смысла, поэтому значение его не важно.

**Comment by AlimovRoostam** [comment]
Спасибо за оперативные ответы) Очень помог) Удачи
